name: Node.js CI/CD

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    # install server dependencies
    - run: npm install
    # install client dependencies
    - run: cd client && npm install --legacy-peer-deps && CI='' npm run build && cd ../
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        MONGODB_USER: ${{ secrets.MONGODB_USER }}
        MONGODB_PWD: ${{ secrets.MONGODB_PWD }}
        REACT_APP_GOOGLE_API_KEY: ${{ secrets.REACT_APP_GOOGLE_API_KEY }}
        REACT_APP_FIREBASE_API_KEY: ${{ secrets.REACT_APP_FIREBASE_API_KEY }}
        REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}
        REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}
        REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.REACT_APP_FIREBASE_STORAGE_BUCKET }}
    
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Update Heroku
      # heroku doesn't always get smoothly installed, so force the install this way
      run: sudo apt install snapd && curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Deploy to Heroku
      # the repo necessary for heroku + github actions
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        # login to heroku using our credentials, then create the necessary heroku git remote
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: travelgram455
        heroku_email: travelgram.cpsc455@gmail.com
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        MONGODB_USER: ${{ secrets.MONGODB_USER }}
        MONGODB_PWD: ${{ secrets.MONGODB_PWD }}
        REACT_APP_GOOGLE_API_KEY: ${{ secrets.REACT_APP_GOOGLE_API_KEY }}
        REACT_APP_FIREBASE_API_KEY: ${{ secrets.REACT_APP_FIREBASE_API_KEY }}
        REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}
        REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}
        REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.REACT_APP_FIREBASE_STORAGE_BUCKET }}
    - name: Add Heroku remote
      run: heroku git:remote --app travelgram455
    - name: Push to Heroku
      run: git push heroku release:master
      # from here on, heroku handles the deployment itself
